export enum Movements {
   steady = "Steady",
   handy = "Handy",
   dollyIn = "Dolly-In",
   dollyOut = "Dolly-Out",
   creaneUp = "Creane-Up",
   creaneDown = "Creane-Down",
   truckLeft = "Truck-Left",
   truckRight = "Truck-Right",
   panClockwise = "Pan-Clockwise",
   panCounterClockwise = "Pan-CounterClockwise",
   tiltUp = "Tilt-Up",
   tiltDown = "Tilt-Down",
   rollClockwise = "Roll-Clockwise",
   rollCounterClockwise = "Roll-CounterClockwise",
   arcClockwise = "Arc-Clockwise",
   arcCounterClockwise = "Arc-CounterClockwise",
}
