scalar Upload

type Project {
    id: Int!
    name: String!
    draft: Float!
    fileId: String
    status: ProjectStatus!
}

enum ProjectStatus {
    pending
    processing
    completed
    error
}

input CreateProjectInput {
    file: Upload!
    name: String!
    draft: Float!
}