type Project {
    id: Int!
    userId: Int!
    name: String!
    draft: String!
    sceneIds: [String!]
    fileId: String
}

input CreateProjectInput {
    userId: Int!
    name: String!
    draft: String!
    sceneIds: [String!]
    fileId: String
}