type Scene {
    id: Int!
    projectId: Int!
    number: Int!
    space: String!
    place: String!
    time: String!
    description: String!
    dialogue: String!
    script: Int!
    talent: [Int]
}

input SceneInput {
    number: Int!
    space: String!
    place: String!
    time: String!
    description: String!
    dialogue: String!
    script: Int!
    talent: [Int]
}

input SceneUpdateInput {
    id: Int!
    number: Int!
    space: String!
    place: String!
    time: String!
    description: String!
    dialogue: String!
    script: Int!
    talent: [Int]
}