type Mutation {
    createShotsMutation(sceneId: Int! shots: [ShotInput]): [Shot]
}

type Mutation {
    updateShotsMutation(sceneId: Int! shots: [ShotInput]): [Shot]
}

type Mutation {
    deleteShotsMutation(sceneId: Int! shotIds: [Int!]): [Shot]
}