type Mutation {
    createShotsMutation(projectId: Int! shots: [Shot]): [Shot]
}

type Mutation {
    updateShotsMutation(sceneId: Int! shots: [ShotInput]): [Shot]
}

type Mutation {
    deleteShotsMutation(sceneId: Int! shotIds: [Int!]): [Shot]
}