type Mutation {
    createShotsMutation(sceneId: Int! shots: [ShotInput]): [Shot]
}

type Mutation {
    updateShotsMutation(shots: [ShotUpdateInput]): [Shot]
}

type Mutation {
    deleteShotsMutation(sceneId: Int! shotIds: [Int!]): [Shot]
}

type Mutation {
    patchShotsMutation(sceneId: Int!, shots: [ShotPatchInput]): [Shot]
}