type Shot {
    id: Int!
    sceneId: Int!,   
    number: String!,
    shot: Shots!
    movement: Movements!,
    angulation: Angulations!,
    action: String,
    dialogue: String,
    sound: Sounds!,
    transition: Transitions,
    notes: String,
    script: Int!,
}

input ShotInput {
    sceneId: Int!,   
    number: String!,
    shot: Shots!
    movement: Movements!,
    angulation: Angulations!,
    action: String,
    dialogue: String,
    sound: Sounds!,
    transition: Transitions!,
    notes: String,
    script: Int!,
}

input ShotUpdateInput {
    id: Int!,
    sceneId: Int!,   
    number: String!,
    shot: Shots!
    movement: Movements!,
    angulation: Angulations!,
    action: String,
    dialogue: String,
    sound: Sounds!,
    transition: Transitions!,
    notes: String,
    script: Int!,
}

input ShotPatchInput { 
    id: Int,
    sceneId: Int!,   
    number: String!,
    shot: Shots!
    movement: Movements!,
    angulation: Angulations!,
    action: String,
    dialogue: String,
    sound: Sounds!,
    transition: Transitions!,
    notes: String,
    script: Int!,
}